declare const theme: {
    $lightBase: string;
    $light1: string;
    $light2: string;
    $light3: string;
    $light4: string;
    $light5: string;
    $light6: string;
    $light7: string;
    $light8: string;
    $light9: string;
    $light10: string;
    $gray1: string;
    $gray2: string;
    $gray3: string;
    $gray4: string;
    $gray5: string;
    $darkBase: string;
    $dark1: string;
    $dark2: string;
    $dark3: string;
    $dark4: string;
    $blueBase: string;
    $redBase: string;
    $pinkBase: string;
    $brandColor: string;
    $brandSecondaryColor: string;
    $contrastiveColor: string;
    $blueColor: string;
    $orangeColor: string;
    $greenColor: string;
    $yellowColor: string;
    $redColor: string;
    $fontColor: string;
    $fontColor1: string;
    $fontColor2: string;
    $fontColor3: string;
    $dangerColor: string;
    $activeBgBase: string;
    $activeBg1: string;
    $activeBg2: string;
    $activeBg3: string;
    $btnDefaultBg: string;
};
export default theme;
export declare const setTheme: (customTheme: any) => void;
